# Generated by Django 4.2.6 on 2023-11-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_reserva', models.DateField()),
                ('hora', models.DateField(blank=True)),
                ('cantidad_personas', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTEN', 'NO ASISTEN')], default='Pendiente', max_length=15, null=True)),
                ('observacion', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
