# Generated by Django 4.2.6 on 2023-11-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=15),
        ),
    ]
