# Generated by Django 4.2.6 on 2023-11-27 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0004_alter_reserva_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad de personas debe ser al menos 1.'), django.core.validators.MaxValueValidator(15, message='La cantidad de personas no puede ser más de 15.')]),
        ),
    ]
