# Generated by Django 4.2.6 on 2023-11-27 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0005_alter_reserva_cantidad_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')]),
        ),
    ]
