# Generated by Django 4.2.6 on 2023-11-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0006_alter_reserva_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
